### ISSUE TITLE
CommandNotFoundError

### ISSUE THREAD

**Issue by HibiVixx** [daddyparodz/AutoDeOldifyLocal#1]
I'm having this problem doing the procedure, but I'm a Ubuntu layman so I'm not sure how to fix it....
```
------READ THIS------
NOW OPEN ANOTHER SHELL, THEN
RUN THE COMMANDS IN THE TXT FILE [ALSO LISTED HERE]
cd DeOldify
conda activate deoldify
jupyter server --generate-config
jupyter server password
jupyter lab
alex@alex-Ubuntu:~/AutoDeOldifyLocal$ cd DeOldify
alex@alex-Ubuntu:~/AutoDeOldifyLocal/DeOldify$ conda activate deoldify
conda: comando não encontrado
alex@alex-Ubuntu:~/AutoDeOldifyLocal/DeOldify$ ~/miniconda3/bin/conda activate deoldify

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


`------READ THIS------
NOW OPEN ANOTHER SHELL, THEN
RUN THE COMMANDS IN THE TXT FILE [ALSO LISTED HERE]
cd DeOldify
conda activate deoldify
jupyter server --generate-config
jupyter server password
jupyter lab
alex@alex-Ubuntu:~/AutoDeOldifyLocal$ cd DeOldify
alex@alex-Ubuntu:~/AutoDeOldifyLocal/DeOldify$ conda activate deoldify
conda: comando não encontrado
alex@alex-Ubuntu:~/AutoDeOldifyLocal/DeOldify$ ~/miniconda3/bin/conda activate deoldify

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


alex@alex-Ubuntu:~/AutoDeOldifyLocal/DeOldify$
```

if you see some snippet in a different language, it's portuguese...

* Comando não encontrado = command not found

Thank you for your attention

👍🏻😎👍🏻

**Comment by daddyparodz** [comment]
Have you tried to open another shell before executing the commands?
It's really important to do it, otherwise they won't work.
If opening another shell doesn't do anything, try to init the shell with
```
conda init bash
```

Then restart the shell and wsl/vm and try again.

**Comment by dcuartielles** [comment]
I confirm I have this same issue with Ubuntu 20.04, even after calling init and restarting the system it won't work

**Comment by techhalloman** [comment]
hi...conda env create -f environment.yml
missing

**Comment by derplayer** [comment]
same problem here on wsl
"conda init bash" does not help

**Comment by daddyparodz** [comment]
Replace env_name with a name of your choice

### create the env
`conda create -n <env_name>`


### check it
`conda info -e`

### activate it
`conda activate <env_name>`

Then open another shell and try again

**Comment by DanialPahlavan** [comment]
> same problem here on wsl "conda init bash" does not help

Hi,Restart WSL or reinstall conda like anaconda

**Comment by EMRD95** [comment]
source ~/.bashrc

**Comment by daddyparodz** [comment]
After restarting the shell or WSL, the problem should go away. Please check the newly updated scripts to see if the issue persists.
